# Generated by Django 5.0.3 on 2024-04-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='email',
            field=models.EmailField(default='harshad@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
